export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const SET_USER = 'SET_USER';
export const SET_USERS = 'SET_USERS';
export const LOADING_USER = 'LOADING_USER';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

export const FETCH_MEET_INITIAL = 'FETCH_MEET_INITIAL';
export const FETCH_MEET_REQUEST = 'FETCH_MEET_REQUEST';
export const FETCH_MEET_SUCCESS = 'FETCH_MEET_SUCCESS';
export const FETCH_MEET_ERROR = 'FETCH_MEET_ERROR';

export const FETCH_MEETS_INITIAL = 'FETCH_MEETS_INITIAL';
export const FETCH_MEETS_REQUEST = 'FETCH_MEETS_REQUEST';
export const FETCH_MEETS_SUCCESS = 'FETCH_MEETS_SUCCESS';
export const FETCH_MEETS_ERROR = 'FETCH_MEETS_ERROR';
export const SET_MEET_ITEMS = 'SET_MEET_ITEMS';
